added feature/dockerize
arslantoor/php-symfony pull request #1
Opened 2021-05-18 06:54 UTC by arslantoor

2021-05-18 13:08 UTC, adeelnawaz commented
- PR and commit titles should be self-explanatory e.g. "Dockerized the app" or "Application dockerization", etc
- Why did you copy the whole nginx-php-fpm into your source? You're supposed to create only a Dockerfile with **base image** set to nginx-php-fpm
- .idea folder should be in gitignore
- Why is there a composer.lock file?

2021-05-18 13:09 UTC, adeelnawaz requested changes
- PR and commit titles should be self-explanatory e.g. "Dockerized the app" or "Application dockerization", etc
- Why did you copy the whole nginx-php-fpm into your source? You're supposed to create only a Dockerfile with base image set to nginx-php-fpm
- .idea folder should be in gitignore
- Why is there a composer.lock file?

2021-05-20 11:09 UTC, adeelnawaz requested changes

2021-05-20 11:09 UTC, adeelnawaz commented on .gitignore
> +###> symfony/framework-bundle ###
What is all this in .gitignore?

2021-05-20 11:09 UTC, adeelnawaz commented on docker-compose.yml.dist
> +  custom-container:
Give your service a proper name, such as testapp or test_app or demo_app etc

2021-05-20 11:09 UTC, adeelnawaz commented on docker-compose.yml.dist
> +    container_name: custom-container
Also container name should be proper

2021-05-20 11:10 UTC, arslantoor commented on docker-compose.yml.dist
> +    container_name: custom-container
okay

2021-05-20 11:29 UTC, arslantoor reviewed
naming convention improve for services in docker-compose.yml.dist

2021-05-20 11:29 UTC, arslantoor commented on .gitignore
> +###> symfony/framework-bundle ###
these are files for symfony

2021-05-26 12:33 UTC, merged