Feature/checklist template
arslantoor/php-symfony pull request #9
Opened 2021-07-06 11:56 UTC by arslantoor

2021-07-06 15:39 UTC, arslantoor commented on assets/app.js
> +import './jquery';
add jquery

2021-07-09 10:37 UTC, adeelnawaz requested changes

2021-07-09 10:37 UTC, adeelnawaz commented on Dockerfile
> +ENV PHP_CATCHALL="1"
Don't set this to 1 in Dockerfile because this will cause the production build to show errors

2021-07-09 10:37 UTC, adeelnawaz commented on Dockerfile
>  WORKDIR /var/www/html/
You can remove this if you want because in base image the workdir is already set to this

2021-07-09 10:37 UTC, adeelnawaz commented on config/packages/prod/webpack_encore.yaml
> +#webpack_encore:
This file should not exist. If needed, add prod configs in main config file with `when@prod`

2021-07-09 10:37 UTC, adeelnawaz commented on config/packages/test/webpack_encore.yaml
> +#webpack_encore:
This file should not exist. If needed, add test configs in main config file with `when@test`

2021-07-09 10:37 UTC, adeelnawaz commented on docker-compose.yml.dist
> +      PGID: 1000
Add a comment on how to get PGID and PUID
```
# How to check GID : execute on host machine `id -g ${whoami}`
# How to check UID : execute on host machine `id -u ${whoami}`
```

2021-07-09 10:37 UTC, adeelnawaz commented on src/Controller/CheckListController.php
> +        return array("task_list" => $task_list);
Prefer PHP7 array syntax and use single quotes
```
['task_list' => $task_list]
```

2021-07-09 10:37 UTC, adeelnawaz commented on src/Controller/HomeController.php
> +     * @Template("index.html.twig")
Template name is not needed. The template should be in the appropriate directory to autoload

2021-07-09 10:37 UTC, adeelnawaz commented on src/Controller/CheckListController.php
> +     * @Template("checklist.html.twig")
Your template annotations should not have a name. Let it autoload, like this
`@Template()`

2021-07-09 10:37 UTC, adeelnawaz commented on templates/base.html.twig
> +{% block nave_bar %}
It's nav, not nave

2021-07-09 10:37 UTC, adeelnawaz commented on templates/base.html.twig
> +{% block javascripts %}
This should be inside body

2021-07-09 10:37 UTC, adeelnawaz commented on templates/checklist.html.twig
> +
Override title block as well, to set title to "Checklists - My Checklist"

2021-07-09 10:37 UTC, adeelnawaz commented on templates/index.html.twig
> +
Override title block to set "Checklists - Home"

2021-07-12 10:16 UTC, merged